---
functional:
  - Пользователь должен иметь возможность зарегистрироваться или авторизоваться
  - Пользователь должен иметь возможность создать игру с необходимыми параметрами
  - Пользователь должен иметь возможность удалить созданную игру
  - Пользователь должен иметь возможность подключиться к игре
  - Пользователь должен иметь возможность отправлять, принимать и отколнять приглашение в игру
  - Пользователь должен иметь возможность писать в чат и личные сообщения
  - Пользователь должен иметь возможность просматривать подробную информацию о турнирах, истории игр, рейтингах пользователей
  - Пользователь должен иметь возможность искать по имени в рейтинге пользователей
  - Пользователь должен иметь возможность фильтровать рейтинг пользователей
  - Пользователь должен видеть два редактора онлайн (свой и соперника)
  - Пользователь должен видеть условие задачи, время и вывод результата
  - Пользователь должен иметь возможность выбрать язык программирования
  - Пользователь должен иметь возможность сдаться, сбросить код и проверить решение
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика 
implicit:
  - Сайт должен корректно выводить информацию полей, кнопок, списков
  - Сайт должен осуществлять корректные переходы по ссылкам и перенаправлять на правильные адреса
  - Сайт должен отображаться на разных языках
  - Сайт должен корректно устанавливать и хранить cookies
