---
functional:
  - Пользователь должен иметь возможность зарегистрироваться/авторизоваться через email, аккаунт GitHub, Discord
  - Пользователь должен иметь возможность создать игру с необходимыми параметрами
  - Пользователь должен иметь возможность удалить созданную игру
  - Пользователь должен иметь возможность подключиться к игре
  - Пользователь должен иметь возможность отправлять, принимать и отколнять приглашение в игру
  - Пользователь должен иметь возможность писать в чат и личные сообщения
  - Пользователь должен иметь возможность просматривать подробную информацию о турнирах, истории игр, рейтингах пользователей
  - Пользователь должен иметь возможность искать по имени в рейтинге пользователей
  - Пользователь должен иметь возможность фильтровать рейтинг пользователей
  - Пользователь должен видеть два редактора онлайн (свой и соперника)
  - Пользователь должен видеть условие задачи, время и вывод результата
  - Пользователь должен иметь возможность выбрать язык программирования из имеющегося списка (python, php, java, c++, ruby, haskell, kotlin, js, go, elexir, c#, clojure, ts, dart, rust)
  - Пользователь должен иметь возможность сдаться, сбросить код и проверить решение
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров (Chrome, Opera, Yandex, Edge, Firefox)
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Сайт должен корректно выводить информацию полей, кнопок, списков
  - Сайт должен осуществлять корректные переходы по ссылкам и перенаправлять на правильные адреса
  - Сайт должен отображаться на разных языках (английский и русский)
  - Сайт должен корректно устанавливать и хранить cookies
